namespace Autumn.Enums;

internal enum CommandID
{
    NewProject,
    OpenProject,
    OpenSettings,
    CloseProject,
    CloseScene,
    Exit,
    AddStage,
    SaveStage,
    Undo,
    Redo,
    AddObject,
    DuplicateObj,
    RemoveObj,
    HideObj,
    ShowAllObjs,
    GotoRelative,
    ToggleSelectAll,
    TranslateObj,
    MoveToPoint,
    RotateObj,
    ScaleObj,
    AddRailPoint,
    ShowHandles,
    CamToObj,
    AddALL,
    SaveALL,
    Search,
    FlyCamMode,
}
